name: CI Build
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Setup .net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0

      - name: Restore NuGet
        run: dotnet restore --locked-mode

      - name: Run tests
        run: dotnet test --no-restore

      - name: Build package
        run: dotnet pack --no-restore --configuration Release --include-symbols RtMidi.Core/RtMidi.Core.csproj

#      - name: Push to nuget.org
#        run: dotnet nuget push --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json RtMidi.Core/bin/Release/*.nupkg