name: CI Tests
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0

      - name: Restore NuGet
        run: dotnet restore --locked-mode

      - name: Run tests
        run: dotnet test --no-restore